version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - uploaded_images:/var/www/html/images/submissions
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploaded_images:

